---
swagger: "2.0"
info:
  description: Contains all available transaction API endpoints in this codebase
  version: 1.0.0
  title: Argent Bank transaction API documentation
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
- http
paths:
  /transactions:
    get:
      tags:
      - Transactions Module
      summary: Get all user transactions
      description: returns an array with all transactions of the logged-in user
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        required: true
        type: string
      security:
      - Bearer: []
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        "400":
          description: Invalid Token
        "500":
          description: Internal Server Error
    put:
      tags:
      - Transactions Module
      summary: Update an existing transaction
      description: api for modify the category or a note of a transaction
      parameters:
      - in: body
        name: body
        description: id, category and note of transaction that needs to edit
        required: true
        schema:
          $ref: '#/definitions/Body'
      - name: Authorization
        in: header
        description: Attach Bearer JWT token
        required: true
        type: string
      security:
      - Bearer: []
      responses:
        "200":
          description: Transactions data retrieved successully
          schema:
            type: array
            items:
              $ref: '#/definitions/EditedTransaction'
        "400":
          description: Invalid id or token supplied
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    properties:
      id:
        type: integer
        example: 105
      date:
        type: string
        example: October 21th, 2022
      description:
        type: string
        example: Golden Sun Bakery
      amount:
        type: integer
        example: 5
      balance:
        type: integer
        example: "2097.55"
      type:
        type: string
        example: Electronic
      Category:
        type: array
        example: ""
      selectedCategory:
        type: string
        example: Food
      note:
        type: string
        example: Main street Food Truck
  Body:
    type: object
    properties:
      id:
        type: integer
        example: 105
      category:
        type: string
        example: Other
      note:
        type: string
        example: Gaz station
  EditedTransaction:
    properties:
      id:
        type: integer
        example: 105
      date:
        type: string
        example: October 21th, 2022
      description:
        type: string
        example: Golden Sun Bakery
      amount:
        type: integer
        example: 5
      balance:
        type: integer
        example: "2097.55"
      type:
        type: string
        example: Electronic
      Category:
        type: array
        example: ""
      selectedCategory:
        type: string
        example: Other
      note:
        type: string
        example: Gaz Station
